services:
  - type: web
    name: angular-service
    env: static
    buildCommand: cd api && npm install && npm run build
    staticPublishPath: /dist
    routes:
      - type: redirect
        source: /
        destination: /index.html

  - type: web
    name: mysql-service
    env: docker
    dockerfilePath: ./back/mysql/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: MENU
      - key: MYSQL_USER
        value: usuario
      - key: MYSQL_PASSWORD
        value: usuario
    disk:
      name: db-storage
      mountPath: /var/lib/mysql
      sizeGB: 10

  - type: web
    name: php-service
    env: docker
    dockerfilePath: ./back/php/Dockerfile
    plan: starter
    autoDeploy: true
    routes:
      - type: http
        source: /
        destination: http://php-service:80
    dependsOn:
      - mysql-service
      - angular-service
